# Automatically generated by SST
# pylint: disable=all
from typing import Any

class Resource:
    class App:
        name: str
        stage: str
    class ChatbotFunction:
        name: str
        type: str
        url: str
    class CounterFunction:
        name: str
        type: str
        url: str
    class Frontend:
        type: str
        url: str
    class VisitorCounter:
        name: str
        type: str

